'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'

interface DownloadSummaryProps {
  analysis: any
  userMode: 'student' | 'startup'
  answers: any
  isDark: boolean
}

export default function DownloadSummary({ analysis, userMode, answers, isDark }: DownloadSummaryProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  // Dynamic color based on recommendation confidence
  const getButtonColor = () => {
    if (!analysis?.options?.[0]) return 'bg-blue-600 hover:bg-blue-700'
    
    const option = analysis.options[0]
    const regretScore = Math.min(
      (option.cost_analysis.monthly_cost_10x / 1000) * 30 +
      (10 - option.technical_analysis.scalability) * 8 +
      (option.technical_analysis.vendor_lockin) * 5,
      100
    )

    if (regretScore < 30) {
      return 'bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700'
    } else if (regretScore < 60) {
      return 'bg-gradient-to-r from-yellow-500 to-orange-600 hover:from-yellow-600 hover:to-orange-700'
    } else {
      return 'bg-gradient-to-r from-red-500 to-pink-600 hover:from-red-600 hover:to-pink-700'
    }
  }

  const generateSummaryText = () => {
    if (!analysis) return ''

    const recommendedStack = analysis.options[0]?.name || 'Recommended Stack'
    const alternativeStack = analysis.options[1]?.name || 'Alternative Stack'
    
    return `
TECH STACK DECISION SUMMARY
Generated by StackReferee

PROJECT CONTEXT:
• Project Type: ${answers.project_type}
• Experience Level: ${answers.experience_level}
• Main Concern: ${answers.main_concern}
• Company Stage: ${answers.company_stage}
• Timeline: ${answers.time_to_market}
• Expected Users: ${answers.expected_users}
• Monthly Budget: $${answers.monthly_budget_usd}

RECOMMENDATION: ${recommendedStack}

COST ANALYSIS:
• Starting Cost: $${analysis.options[0]?.cost_analysis.monthly_cost_current}/month
• At Scale: $${analysis.options[0]?.cost_analysis.monthly_cost_10x}/month

KEY REASONING:
${userMode === 'student' 
  ? `• Fits academic timeline and learning objectives
• Excellent documentation and community support
• Free tier suitable for project requirements
• Easy to explain in viva/interviews`
  : `• Balances development speed with cost control
• Scalable architecture for business growth
• Migration paths available if needed
• Fits current team expertise level`
}

ALTERNATIVE CONSIDERED: ${alternativeStack}
• Why not chosen: ${userMode === 'student' 
  ? 'Steeper learning curve and fewer beginner resources'
  : 'Higher scaling costs or complexity for current needs'
}

${userMode === 'student' ? `
VIVA PREPARATION:
Q: "Why did you choose ${recommendedStack}?"
A: "I evaluated multiple options based on project timeline, learning curve, and cost constraints. ${recommendedStack} provided the best balance of development speed and educational value."

Q: "What are the trade-offs?"
A: "While ${alternativeStack} might offer more control, ${recommendedStack} reduces complexity and allows me to focus on core functionality within the project deadline."
` : `
BUSINESS CONSIDERATIONS:
• Regret Risk: Low - Well-suited for current stage
• Scaling Path: Clear migration options available
• Team Readiness: Matches current skill level
• Cost Predictability: Transparent pricing model
`}

Generated on: ${new Date().toLocaleDateString()}
Visit: stackreferee.com for more decisions
    `.trim()
  }

  const downloadSummary = async () => {
    setIsGenerating(true)
    
    try {
      const summaryText = generateSummaryText()
      
      // Create and download file
      const blob = new Blob([summaryText], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `tech-stack-decision-${Date.now()}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      
      // Show success feedback
      setTimeout(() => setIsGenerating(false), 1000)
    } catch (error) {
      console.error('Failed to generate summary:', error)
      setIsGenerating(false)
    }
  }

  if (!analysis) return null

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.8 }}
      className="flex justify-center mt-8"
    >
      <motion.button
        onClick={downloadSummary}
        disabled={isGenerating}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className={`
          ${getButtonColor()}
          text-white font-semibold py-4 px-8 rounded-xl
          shadow-lg hover:shadow-xl
          transition-all duration-300
          disabled:opacity-70 disabled:cursor-not-allowed
          flex items-center space-x-3
          relative overflow-hidden
        `}
      >
        {/* Animated background effect */}
        <motion.div
          className="absolute inset-0 bg-white opacity-0 hover:opacity-10"
          whileHover={{ opacity: 0.1 }}
          transition={{ duration: 0.3 }}
        />
        
        {/* Button content */}
        <motion.div
          animate={isGenerating ? { rotate: 360 } : { rotate: 0 }}
          transition={{ duration: 1, repeat: isGenerating ? Infinity : 0, ease: "linear" }}
        >
          {isGenerating ? (
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24">
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              />
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              />
            </svg>
          ) : (
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          )}
        </motion.div>
        
        <span className="relative z-10">
          {isGenerating ? 'Generating...' : 'Download Summary'}
        </span>
        
        {/* Sparkle effect */}
        {!isGenerating && (
          <motion.div
            className="absolute top-1 right-1 w-2 h-2 bg-white rounded-full opacity-0"
            animate={{ 
              opacity: [0, 1, 0],
              scale: [0.5, 1, 0.5]
            }}
            transition={{ 
              duration: 2,
              repeat: Infinity,
              delay: Math.random() * 2
            }}
          />
        )}
      </motion.button>
    </motion.div>
  )
}